"""empty message

Revision ID: 06088a20f2ac
Revises: d31d62c3f7f4
Create Date: 2021-11-18 01:25:21.075932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06088a20f2ac'
down_revision = 'd31d62c3f7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
