"""empty message

Revision ID: 06c4d3370c91
Revises: 9e7842c11943
Create Date: 2021-11-18 02:54:13.568896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c4d3370c91'
down_revision = '9e7842c11943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('comment', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('autor', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
