"""empty message

Revision ID: 9e7842c11943
Revises: 06088a20f2ac
Create Date: 2021-11-18 02:15:58.251335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7842c11943'
down_revision = '06088a20f2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('autor', sa.String(length=140), nullable=True))
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('comment', 'autor')
    # ### end Alembic commands ###
